Repository TeamDearToday/Deartoday-iOS, pull requests merged in 2022-07, with the labels that each got.

#6 [#5] Apple Push Notification 구현
  Deartoday/Deartoday.xcodeproj/project.pbxproj
  Deartoday/Deartoday/GoogleService-Info.plist
  Deartoday/Deartoday/Resource/Support/AppDelegate.swift
Labels: 소깡, 코드리뷰, P0, 프로젝트

#12 [#8] 디자인시스템 구현 및 적용
  Deartoday/Deartoday.xcodeproj/project.pbxproj
  Deartoday/Deartoday/Global/DesignSystem/DDSButton.swift
  Deartoday/Deartoday/Global/DesignSystem/DDSTextField.swift
  Deartoday/Deartoday/Global/Extension/UITextField+.swift
  Deartoday/Deartoday/Screen/TimeTravel/Controller/TimeTravelViewController.swift
  Deartoday/Deartoday/Screen/TimeTravel/Model/TimeTravelDataModel.swift
  Deartoday/Deartoday/Screen/TimeTravel/View/TimeTravelView.swift
Labels: 소깡, 레이아웃, 코드리뷰, P0

#13 [Chore] Font 추가
  Deartoday/Deartoday.xcodeproj/project.pbxproj
  Deartoday/Deartoday/Global/Constant/Image.swift
  Deartoday/Deartoday/Global/Extension/UIColor+.swift
  Deartoday/Deartoday/Global/Extension/UIFont+.swift
  Deartoday/Deartoday/Resource/Font/GmarketSansBold.otf
  Deartoday/Deartoday/Resource/Font/GmarketSansMedium.otf
  Deartoday/Deartoday/Resource/Font/Pretendard-Bold.otf
  Deartoday/Deartoday/Resource/Font/Pretendard-Medium.otf
  Deartoday/Deartoday/Resource/Font/Pretendard-Regular.otf
  Deartoday/Deartoday/Resource/Font/Pretendard-SemiBold.otf
  Deartoday/Deartoday/Resource/Font/TempFont.swift
  Deartoday/Deartoday/Resource/Support/Info.plist
Labels: 경만, 코드리뷰, 프로젝트

#16 [Feat] Main UI 구현
  Deartoday/Deartoday.xcodeproj/project.pbxproj
  Deartoday/Deartoday/Global/Extension/UIViewController+.swift
  Deartoday/Deartoday/Screen/Main/Base.lproj/Main.storyboard
  Deartoday/Deartoday/Screen/Main/Controller/MainViewController.swift
Labels: 경만, 레이아웃, 코드리뷰, P0

#21 [Feat] Custom Alert 구현
  Deartoday/Deartoday.xcodeproj/project.pbxproj
  Deartoday/Deartoday/Resource/Support/SceneDelegate.swift
  Deartoday/Deartoday/Screen/DeartodayAlert/Controller/DeartodayAlertViewController.swift
  Deartoday/Deartoday/Screen/DeartodayAlert/Model/DeartodayModel.swift
Labels: 경만, 코드리뷰, P0, 프로젝트

#19 [Feat] 시간여행 UI 구현 (#4)
  Deartoday/Deartoday.xcodeproj/project.pbxproj
  Deartoday/Deartoday/Resource/Support/Info.plist
  Deartoday/Deartoday/Screen/TimeTravel/Controller/TimeTravelViewController.swift
  Deartoday/Deartoday/Screen/TimeTravel/View/CountDownLabel.swift
  Deartoday/Deartoday/Screen/TimeTravel/View/TimeTravelView.swift
Labels: 소깡, 레이아웃, 코드리뷰, P0

#23 [Feat] 온보딩 UI 구현
  Deartoday/Deartoday.xcodeproj/project.pbxproj
  Deartoday/Deartoday/Screen/Onboarding/Controller/OnboardingViewController.swift
  Deartoday/Deartoday/Screen/Onboarding/Onboarding.storyboard
Labels: 찬마, 레이아웃, 코드리뷰, P0, 프로젝트

#25 [Feat] Check Message Empty 뷰 구현
  Deartoday/Deartoday.xcodeproj/project.pbxproj
  Deartoday/Deartoday/Global/Extension/UILabel+.swift
  Deartoday/Deartoday/Screen/CheckMessage/CheckMessage.storyboard
  Deartoday/Deartoday/Screen/CheckMessage/Controller/CheckMessageViewController.swift
  Deartoday/Deartoday/Screen/CheckMessage/Model/CheckMessageDataModel.swift
  Deartoday/Deartoday/Screen/CheckMessage/View/CheckMessageView.swift
Labels: 경만, 레이아웃, 코드리뷰, P0

#29 [Feat] 시간여행 확인 Empty View 구현
  Deartoday/Deartoday.xcodeproj/project.pbxproj
  Deartoday/Deartoday/Screen/CheckTimeTravel/CheckTimeTravel.storyboard
  Deartoday/Deartoday/Screen/CheckTimeTravel/Controller/CheckTimeTravelViewController.swift
  Deartoday/Deartoday/Screen/CheckTimeTravel/Model/CheckTImeTravelDataModel.swift
  Deartoday/Deartoday/Screen/CheckTimeTravel/View/CheckTimeTravelView.swift
Labels: 경만, 레이아웃, 코드리뷰, P0

#28 [Chore] 온보딩 UI 코드리뷰 반영
  Deartoday/Deartoday/Screen/Onboarding/Controller/OnboardingViewController.swift
  Deartoday/Deartoday/Screen/Onboarding/Onboarding.storyboard
Labels: 찬마, 레이아웃, 코드리뷰, P0

#33 [Feat] circle custom button 구현
  Deartoday/Deartoday/Screen/Onboarding/Controller/OnboardingViewController.swift
  Deartoday/Deartoday/Screen/Onboarding/Onboarding.storyboard
Labels: 찬마, 레이아웃, 코드리뷰, P0, 프로젝트

#34 [Feat] Check Message Detail View UI 구현
  Deartoday/Deartoday.xcodeproj/project.pbxproj
  Deartoday/Deartoday/Screen/CheckMessageDetail/CheckMessageDetail.storyboard
  Deartoday/Deartoday/Screen/CheckMessageDetail/Controller/CheckMessageDetailViewController.swift
  Deartoday/Deartoday/Screen/CheckMessageDetail/View/CheckMessageDetailView.swift
Labels: 경만, 레이아웃, 코드리뷰, P0

#37 [Feat] 메인뷰 화면전환 플로우 추가
  Deartoday/Deartoday/Screen/CheckMessage/CheckMessage.storyboard
  Deartoday/Deartoday/Screen/CheckMessage/Controller/CheckMessageViewController.swift
  Deartoday/Deartoday/Screen/CheckTimeTravel/CheckTimeTravel.storyboard
  Deartoday/Deartoday/Screen/CheckTimeTravel/Controller/CheckTimeTravelViewController.swift
  Deartoday/Deartoday/Screen/Main/Controller/MainViewController.swift
  Deartoday/Deartoday/Screen/TimeTravel/Controller/TimeTravelViewController.swift
Labels: 경만, 코드리뷰, P0, 프로젝트

#40 [Feat] 온보딩 편지 UI
  Deartoday/Deartoday.xcodeproj/project.pbxproj
  Deartoday/Deartoday/Global/Constant/ViewController.swift
  Deartoday/Deartoday/Screen/Onboarding/Controller/LetterOnboardingViewController.swift
  Deartoday/Deartoday/Screen/Onboarding/Controller/OnboardingViewController.swift
  Deartoday/Deartoday/Screen/Onboarding/Controller/OpenBoxOnboardingViewController.swift
  Deartoday/Deartoday/Screen/Onboarding/Onboarding.storyboard
Labels: 소깡, 찬마, 레이아웃, 코드리뷰, P0, 프로젝트

#42 [Feat] 온보딩 첫번째 편지 UI 구현
  Deartoday/Deartoday/Screen/Onboarding/Controller/LetterOnboardingViewController.swift
  Deartoday/Deartoday/Screen/Onboarding/Controller/OnboardingViewController.swift
  Deartoday/Deartoday/Screen/Onboarding/Controller/OpenBoxOnboardingViewController.swift
  Deartoday/Deartoday/Screen/Onboarding/Onboarding.storyboard
Labels: 찬마, 레이아웃, 코드리뷰, P0, 프로젝트

#44 [#31] conflict 해결
  Deartoday/Deartoday/Screen/Onboarding/Onboarding.storyboard
Labels: 경만

#48 [Chore] 온보딩 버튼 title 수정
  Deartoday/Deartoday/Screen/Onboarding/Controller/LetterOnboardingViewController.swift
  Deartoday/Deartoday/Screen/Onboarding/Controller/OnboardingViewController.swift
  Deartoday/Deartoday/Screen/Onboarding/Controller/OpenBoxOnboardingViewController.swift
  Deartoday/Deartoday/Screen/Onboarding/Onboarding.storyboard
Labels: 찬마, 레이아웃, 코드리뷰, 오류해결, P0, 프로젝트

#50 [Feat] Empty view 화면 전환 추가
  Deartoday/Deartoday/Screen/CheckMessage/CheckMessage.storyboard
  Deartoday/Deartoday/Screen/CheckMessage/Controller/CheckMessageViewController.swift
  Deartoday/Deartoday/Screen/CheckTimeTravel/CheckTimeTravel.storyboard
  Deartoday/Deartoday/Screen/CheckTimeTravel/Controller/CheckTimeTravelViewController.swift
Labels: 경만, 코드리뷰, P0

#54 [Feat] 메시지 확인 뷰 구현
  Deartoday/Deartoday.xcodeproj/project.pbxproj
  Deartoday/Deartoday/Screen/CheckMessage/CheckMessage.storyboard
  Deartoday/Deartoday/Screen/CheckMessage/Controller/CheckMessageViewController.swift
  Deartoday/Deartoday/Screen/CheckMessage/View/MessageCollectionViewCell.swift
  Deartoday/Deartoday/Screen/CheckMessage/View/MessageCollectionViewCell.xib
  Deartoday/Deartoday/Screen/CheckTimeTravel/Controller/CheckTimeTravelViewController.swift
Labels: 경만, 레이아웃, 코드리뷰, P0

#57 [Feat] 시간여행 대화방 애니메이션 구현 (#45)
  Deartoday/Deartoday/Screen/Dialog/Controller/DialogViewController+.swift
  Deartoday/Deartoday/Screen/Dialog/Controller/DialogViewController.swift
  Deartoday/Deartoday/Screen/Dialog/Model/DialogDataModel.swift
  Deartoday/Deartoday/Screen/Dialog/View/DialogMessageView.swift
Labels: 소깡, 레이아웃, 코드리뷰, P0

#59 [Feat] 온보딩 편지 UI
  Deartoday/Deartoday.xcodeproj/project.pbxproj
  Deartoday/Deartoday/Global/Constant/ViewController.swift
  Deartoday/Deartoday/Screen/Onboarding/Controller/LetterOnboardingViewController.swift
  Deartoday/Deartoday/Screen/Onboarding/Controller/OpenBoxOnboardingViewController.swift
  Deartoday/Deartoday/Screen/Onboarding/Controller/PlayTapeOnboardingViewController.swift
  Deartoday/Deartoday/Screen/Onboarding/Onboarding.storyboard
Labels: 찬마, 레이아웃, 코드리뷰, P0, 프로젝트

#60 [Feat] 레이아웃 디테일 잡기
  Deartoday/Deartoday/Resource/Asset/Assets.xcassets/icRewind.imageset/Contents.json
  Deartoday/Deartoday/Resource/Asset/Assets.xcassets/icnMemo.imageset/Contents.json
  Deartoday/Deartoday/Resource/Asset/Assets.xcassets/icnTape.imageset/Contents.json
  Deartoday/Deartoday/Screen/CheckMessage/View/MessageCollectionViewCell.swift
  Deartoday/Deartoday/Screen/CheckMessage/View/MessageCollectionViewCell.xib
  Deartoday/Deartoday/Screen/Main/Base.lproj/Main.storyboard
  Deartoday/Deartoday/Screen/Main/Controller/MainViewController.swift
Labels: 경만, 레이아웃, 코드리뷰, P0

#62 [Feat] 시간여행 가상공간 로티 구현 (#58)
  Deartoday/Deartoday/Screen/TimeTravel/Controller/TimeTravelViewController.swift
  Deartoday/Deartoday/Screen/VirtualSpace/Controller/VirtualSpaceViewController.swift
Labels: 소깡, 코드리뷰, P0

#63 [Feat] 온보딩 로티 구현
  Deartoday/Deartoday/Screen/Onboarding/Controller/LetterOnboardingViewController.swift
  Deartoday/Deartoday/Screen/Onboarding/Controller/OnboardingViewController.swift
  Deartoday/Deartoday/Screen/Onboarding/Controller/PlayTapeOnboardingViewController.swift
  Deartoday/Deartoday/Screen/Onboarding/Onboarding.storyboard
Labels: 찬마, 레이아웃, 코드리뷰, P0, 프로젝트

#69 [#66] 시간여행 가상공간 이미지 GET 파일 추가
  Deartoday/Deartoday.xcodeproj/project.pbxproj
  Deartoday/Deartoday/Network/API/TimeTravel/TimeTravelAPI.swift
  Deartoday/Deartoday/Network/Base/BaseTargetType.swift
  Deartoday/Deartoday/Network/Base/NetworkConstant.swift
  Deartoday/Deartoday/Network/Base/URLConstant.swift
  Deartoday/Deartoday/Network/DataModel/TimeTravel/TimeTravelResponse.swift
  Deartoday/Deartoday/Network/Service/TimeTravel/TimeTravelService.swift
  Deartoday/Deartoday/Screen/VirtualSpace/Controller/VirtualSpaceViewController.swift
Labels: 소깡, 서버통신, P0

#70 [Feat] 시간여행 가상공간 이미지 GET 서버통신 (#66)
  Deartoday/Deartoday/Network/Base/NetworkConstant.swift
  Deartoday/Deartoday/Screen/VirtualSpace/Controller/VirtualSpaceViewController.swift
  Deartoday/Deartoday/Screen/VirtualSpace/View/VirtualSpaceCollectionViewCell.swift
Labels: 소깡, 서버통신, P0

#73 [Feat] Main 서버 연결
  Deartoday/Deartoday.xcodeproj/project.pbxproj
  Deartoday/Deartoday/Network/API/Main/MainAPI.swift
  Deartoday/Deartoday/Network/API/TempAPI.swift
  Deartoday/Deartoday/Network/Base/URLConstant.swift
  Deartoday/Deartoday/Network/DataModel/Main/MainResponse.swift
  Deartoday/Deartoday/Network/DataModel/TempDataModel.swift
  Deartoday/Deartoday/Network/Service/Main/MainService.swift
  Deartoday/Deartoday/Network/Service/TempService.swift
  Deartoday/Deartoday/Screen/Main/Controller/MainViewController.swift
Labels: 경만, 서버통신, 코드리뷰, P0

#74 [Feat] 시간여행 가상공간 Question GET 서버통신 (#71)
  Deartoday/Deartoday.xcodeproj/project.pbxproj
  Deartoday/Deartoday/Network/API/TimeTravel/TimeTravelAPI.swift
  Deartoday/Deartoday/Network/Base/NetworkConstant.swift
  Deartoday/Deartoday/Network/Base/URLConstant.swift
  Deartoday/Deartoday/Network/DataModel/TimeTravel/TimeTravelQuestionResponse.swift
  Deartoday/Deartoday/Network/Service/TimeTravel/TimeTravelService.swift
  Deartoday/Deartoday/Screen/Dialog/Controller/DialogViewController.swift
Labels: 소깡, 서버통신, P0

#77 [Feat] 시간여행 확인 목록 서버 연결
  Deartoday/Deartoday.xcodeproj/project.pbxproj
  Deartoday/Deartoday/Network/API/CheckTimeTravel/CheckTimeTravelAPI.swift
  Deartoday/Deartoday/Network/Base/URLConstant.swift
  Deartoday/Deartoday/Network/DataModel/CheckTimeTravel/CheckTimeTravelResponse.swift
  Deartoday/Deartoday/Network/Service/CheckTimeTravel/CheckTimeTravelService.swift
  Deartoday/Deartoday/Screen/CheckTimeTravel/CheckTimeTravel.storyboard
  Deartoday/Deartoday/Screen/CheckTimeTravel/Controller/CheckTimeTravelViewController.swift
  Deartoday/Deartoday/Screen/CheckTimeTravel/Model/CheckTImeTravelDataModel.swift
  Deartoday/Deartoday/Screen/CheckTimeTravel/View/TimeTapeTableViewCell.swift
  Deartoday/Deartoday/Screen/CheckTimeTravel/View/TimeTapeTableViewCell.xib
  Deartoday/Deartoday/Screen/Main/Controller/MainViewController.swift
Labels: 경만, 서버통신, 코드리뷰, P0

#82 [Feat] 애플로그인 구현
  Deartoday/Deartoday.xcodeproj/project.pbxproj
  Deartoday/Deartoday/Network/API/Login/LoginAPI.swift
  Deartoday/Deartoday/Network/Base/URLConstant.swift
  Deartoday/Deartoday/Network/DataModel/Login/LoginRequest.swift
  Deartoday/Deartoday/Network/DataModel/Login/LoginResponse.swift
  Deartoday/Deartoday/Network/Service/Login/LoginService.swift
  Deartoday/Deartoday/Resource/Support/AppDelegate.swift
  Deartoday/Deartoday/Resource/Support/SceneDelegate.swift
  Deartoday/Deartoday/Screen/Initial/Controller/InitialViewContoller.swift
Labels: 찬마, 레이아웃, 서버통신, 코드리뷰, P0, 프로젝트

#85 [#80] 터치영역 안눌리는 문제 수정
  Deartoday/Deartoday/Screen/Main/Base.lproj/Main.storyboard
Labels: 경만, 서버통신, 코드리뷰, P0

#86 [Feat] 메시지 데이터 전달
  Deartoday/Deartoday/Network/Base/NetworkConstant.swift
  Deartoday/Deartoday/Screen/CheckMessage/Controller/CheckMessageViewController.swift
Labels: 경만, 코드리뷰, P0, 프로젝트

#92 [Feat] 시간 여행 상세 확인 서버 연결
  Deartoday/Deartoday.xcodeproj/project.pbxproj
  Deartoday/Deartoday/Global/Constant/Storyboard.swift
  Deartoday/Deartoday/Global/Constant/ViewController.swift
  Deartoday/Deartoday/Network/API/CheckTimeTravel/CheckTimeTravelAPI.swift
  Deartoday/Deartoday/Network/Base/NetworkConstant.swift
  Deartoday/Deartoday/Network/DataModel/CheckMessage/CheckMessageResponse.swift
  Deartoday/Deartoday/Network/DataModel/CheckTimeTravel/CheckTimeTravelDetailResponse.swift
  Deartoday/Deartoday/Network/Service/CheckTimeTravel/CheckTimeTravelService.swift
  Deartoday/Deartoday/Resource/Support/SceneDelegate.swift
  Deartoday/Deartoday/Screen/CheckTimeTravel/Controller/CheckTimeTravelViewController.swift
  Deartoday/Deartoday/Screen/CheckTimeTravelDetail/CheckTimeTravelDetail.storyboard
  Deartoday/Deartoday/Screen/CheckTimeTravelDetail/Controller/CheckTimeTravelDetailViewController.swift
  Deartoday/Deartoday/Screen/CheckTimeTravelDetail/Model/CheckTimeTravelDetailDataModel.swift
  Deartoday/Deartoday/Screen/CheckTimeTravelDetail/View/PastImageCollectionViewCell.swift
  Deartoday/Deartoday/Screen/CheckTimeTravelDetail/View/TimeTravelChatCollectionViewCell.swift
  Deartoday/Deartoday/Screen/CheckTimeTravelDetail/View/TimeTravelChatCollectionViewCell.xib
  Deartoday/Deartoday/Screen/CheckTimeTravelDetail/View/TimeTravelInfoView.swift
  Deartoday/Deartoday/Screen/CheckTimeTravelDetail/View/TimeTravelLastAnswerCollectionViewCell.swift
  Deartoday/Deartoday/Screen/CheckTimeTravelDetail/View/TimeTravelLastAnswerCollectionViewCell.xib
Labels: 경만, 서버통신, 코드리뷰, P0

#93 [#76] 시간여행 가상공간 POST
  Deartoday/Deartoday.xcodeproj/project.pbxproj
  Deartoday/Deartoday/Network/API/TimeTravel/TimeTravelAPI.swift
  Deartoday/Deartoday/Network/Base/NetworkConstant.swift
  Deartoday/Deartoday/Network/Base/URLConstant.swift
  Deartoday/Deartoday/Network/DataModel/TimeTravel/TimeTravelAnswerRequest.swift
  Deartoday/Deartoday/Network/DataModel/TimeTravel/TimeTravelAnswerResponse.swift
  Deartoday/Deartoday/Network/Service/TimeTravel/TimeTravelService.swift
  Deartoday/Deartoday/Resource/Asset/Assets.xcassets/AppIcon.appiconset/Contents.json
  Deartoday/Deartoday/Screen/CheckTimeTravel/Controller/CheckTimeTravelViewController.swift
  Deartoday/Deartoday/Screen/Dialog/Controller/DialogViewController.swift
  Deartoday/Deartoday/Screen/TimeTravel/Controller/TimeTravelViewController.swift
  Deartoday/Deartoday/Screen/VirtualSpace/Controller/VirtualSpaceViewController.swift
Labels: 소깡, 서버통신, P0

#95 [#94] 시간여행 비디오테이프 사운드 실행
  Deartoday/Deartoday/Screen/TimeTravel/Controller/TimeTravelViewController.swift
Labels: 소깡, 코드리뷰, P0

#97 [Feat] 시간여행 상세 image, title, 마지막 말 cell 구현
  Deartoday/Deartoday.xcodeproj/project.pbxproj
  Deartoday/Deartoday/Global/Constant/Image.swift
  Deartoday/Deartoday/Network/Base/NetworkConstant.swift
  Deartoday/Deartoday/Resource/Asset/Assets.xcassets/imgTextBoxPast.imageset/Contents.json
  Deartoday/Deartoday/Resource/Asset/Assets.xcassets/imgTextBoxPast.imageset/imgTextBoxPast.png
  Deartoday/Deartoday/Resource/Asset/Assets.xcassets/imgTextBoxPast.imageset/imgTextBoxPast@2x.png
  Deartoday/Deartoday/Resource/Asset/Assets.xcassets/imgTextBoxPast.imageset/imgTextBoxPast@3x.png
  Deartoday/Deartoday/Resource/Asset/Assets.xcassets/imgTextBoxPresent.imageset/Contents.json
  Deartoday/Deartoday/Resource/Asset/Assets.xcassets/imgTextBoxPresent.imageset/imgTextBoxPresent.png
  Deartoday/Deartoday/Resource/Asset/Assets.xcassets/imgTextBoxPresent.imageset/imgTextBoxPresent@2x.png
  Deartoday/Deartoday/Resource/Asset/Assets.xcassets/imgTextBoxPresent.imageset/imgTextBoxPresent@3x.png
  Deartoday/Deartoday/Screen/CheckTimeTravel/Controller/CheckTimeTravelViewController.swift
  Deartoday/Deartoday/Screen/CheckTimeTravelDetail/CheckTimeTravelDetail.storyboard
  Deartoday/Deartoday/Screen/CheckTimeTravelDetail/Controller/CheckTimeTravelDetailViewController.swift
  Deartoday/Deartoday/Screen/CheckTimeTravelDetail/Model/CheckTimeTravelDetailDataModel.swift
  Deartoday/Deartoday/Screen/CheckTimeTravelDetail/View/PastImageCollectionViewCell.swift
  Deartoday/Deartoday/Screen/CheckTimeTravelDetail/View/PastImageCollectionViewCell.xib
  Deartoday/Deartoday/Screen/CheckTimeTravelDetail/View/TravelAnswerCollectionViewCell.swift
  Deartoday/Deartoday/Screen/CheckTimeTravelDetail/View/TravelAnswerCollectionViewCell.xib
  Deartoday/Deartoday/Screen/CheckTimeTravelDetail/View/TravelInfoCollectionViewCell.swift
  Deartoday/Deartoday/Screen/CheckTimeTravelDetail/View/TravelInfoCollectionViewCell.xib
  Deartoday/Deartoday/Screen/CheckTimeTravelDetail/View/TravelLastCollectionViewCell.swift
  Deartoday/Deartoday/Screen/CheckTimeTravelDetail/View/TravelLastCollectionViewCell.xib
Labels: 경만, 레이아웃, 코드리뷰, P0

#98 [Feat] 시간여행 팝업창 화면 전환
  Deartoday/Deartoday/Screen/DeartodayAlert/Controller/DeartodayAlertViewController.swift
  Deartoday/Deartoday/Screen/Dialog/Controller/DialogViewController.swift
  Deartoday/Deartoday/Screen/TimeTravel/Controller/TimeTravelViewController.swift
  Deartoday/Deartoday/Screen/VirtualSpace/Controller/VirtualSpaceViewController.swift
Labels: 소깡, 코드리뷰, P0

#105 [Feat] 셀 토대.. 1차 머지
  Deartoday/Deartoday.xcodeproj/project.pbxproj
  Deartoday/Deartoday/Network/Base/NetworkConstant.swift
  Deartoday/Deartoday/Resource/Asset/Assets.xcassets/imgTextBoxPast.imageset/Contents.json
  Deartoday/Deartoday/Resource/Asset/Assets.xcassets/imgTextBoxPresent.imageset/Contents.json
  Deartoday/Deartoday/Resource/Asset/Assets.xcassets/imgTextBoxPresent.imageset/imgTextBoxPresent.png
  Deartoday/Deartoday/Resource/Asset/Assets.xcassets/imgTextBoxPresent.imageset/imgTextBoxPresent@2x.png
  Deartoday/Deartoday/Resource/Asset/Assets.xcassets/imgTextBoxPresent.imageset/imgTextBoxPresent@3x.png
  Deartoday/Deartoday/Screen/CheckTimeTravel/Controller/CheckTimeTravelViewController.swift
  Deartoday/Deartoday/Screen/CheckTimeTravelDetail/Controller/CheckTimeTravelDetailViewController.swift
  Deartoday/Deartoday/Screen/CheckTimeTravelDetail/View/PastDialogCollectionViewCell.swift
  Deartoday/Deartoday/Screen/CheckTimeTravelDetail/View/PastDialogCollectionViewCell.xib
  Deartoday/Deartoday/Screen/CheckTimeTravelDetail/View/PresentDialogCollectionViewCell.swift
  Deartoday/Deartoday/Screen/CheckTimeTravelDetail/View/PresentDialogCollectionViewCell.xib
  Deartoday/Deartoday/Screen/CheckTimeTravelDetail/View/TravelAnswerCollectionViewCell.swift
  Deartoday/Deartoday/Screen/CheckTimeTravelDetail/View/TravelAnswerCollectionViewCell.xib
  Deartoday/Deartoday/Screen/CheckTimeTravelDetail/View/TravelChatCollectionViewCell.swift
  Deartoday/Deartoday/Screen/CheckTimeTravelDetail/View/TravelChatCollectionViewCell.xib
  Deartoday/Deartoday/Screen/CheckTimeTravelDetail/View/TravelInfoCollectionReusableView.swift
  Deartoday/Deartoday/Screen/CheckTimeTravelDetail/View/TravelInfoCollectionReusableView.xib
  Deartoday/Deartoday/Screen/CheckTimeTravelDetail/View/TravelLastCollectionViewCell.swift
Labels: 경만, 서버통신, 코드리뷰, P0

#106 [Feat] API Model 변경사항 반영
  Deartoday/Deartoday.xcodeproj/project.pbxproj
  Deartoday/Deartoday/Network/API/CheckMessage/CheckMessageAPI.swift
  Deartoday/Deartoday/Network/DataModel/CheckMessage/CheckMessageResponse.swift
  Deartoday/Deartoday/Screen/CheckMessage/Controller/CheckMessageViewController.swift
  Deartoday/Deartoday/Screen/CheckMessage/Model/CheckMessageDataModel.swift
Labels: 경만, 서버통신, 코드리뷰, P0

#107 [Feat] Flow 관련 작업
  Deartoday/Deartoday/Screen/Main/Base.lproj/Main.storyboard
  Deartoday/Deartoday/Screen/Main/Controller/MainViewController.swift
Labels: 경만, 코드리뷰, P0, 프로젝트

#109 [Feat] 온보딩 기기대응 UI 구현
  Deartoday/Deartoday/Screen/Onboarding/Controller/OnboardingViewController.swift
  Deartoday/Deartoday/Screen/Onboarding/Controller/PlayTapeOnboardingViewController.swift
  Deartoday/Deartoday/Screen/Onboarding/Onboarding.storyboard
Labels: 찬마, 레이아웃, P0, 프로젝트

#110 [Feat] Section Header 설정
  Deartoday/Deartoday/Screen/CheckTimeTravelDetail/Controller/CheckTimeTravelDetailViewController.swift
  Deartoday/Deartoday/Screen/CheckTimeTravelDetail/View/PastImageCollectionViewCell.swift
  Deartoday/Deartoday/Screen/CheckTimeTravelDetail/View/TravelInfoCollectionReusableView.swift
  Deartoday/Deartoday/Screen/CheckTimeTravelDetail/View/TravelInfoCollectionReusableView.xib
Labels: 경만, 레이아웃, 코드리뷰, P0

#111 [Feat] UI Setting + 마지막 말 말풍선 크기
  Deartoday/Deartoday/Resource/Asset/Assets.xcassets/imgTextBoxPast.imageset/Contents.json
  Deartoday/Deartoday/Resource/Asset/Assets.xcassets/imgTextBoxPresent.imageset/Contents.json
  Deartoday/Deartoday/Screen/CheckTimeTravelDetail/CheckTimeTravelDetail.storyboard
  Deartoday/Deartoday/Screen/CheckTimeTravelDetail/Controller/CheckTimeTravelDetailViewController.swift
  Deartoday/Deartoday/Screen/CheckTimeTravelDetail/View/PastDialogCollectionViewCell.swift
  Deartoday/Deartoday/Screen/CheckTimeTravelDetail/View/PastDialogCollectionViewCell.xib
  Deartoday/Deartoday/Screen/CheckTimeTravelDetail/View/PresentDialogCollectionViewCell.swift
  Deartoday/Deartoday/Screen/CheckTimeTravelDetail/View/PresentDialogCollectionViewCell.xib
  Deartoday/Deartoday/Screen/CheckTimeTravelDetail/View/TravelAnswerCollectionViewCell.swift
  Deartoday/Deartoday/Screen/CheckTimeTravelDetail/View/TravelAnswerCollectionViewCell.xib
  Deartoday/Deartoday/Screen/CheckTimeTravelDetail/View/TravelInfoCollectionReusableView.xib
Labels: 경만, 레이아웃, 코드리뷰, P0

#112 [#108] sizetofit method 호출 추가
  Deartoday/Deartoday/Screen/CheckTimeTravelDetail/View/TravelAnswerCollectionViewCell.swift
Labels: 경만, 레이아웃, 코드리뷰, P0

#113 [Feat] 시간 여행 상세 뷰 UI
  Deartoday/Deartoday/Network/Base/NetworkConstant.swift
  Deartoday/Deartoday/Screen/CheckTimeTravelDetail/CheckTimeTravelDetail.storyboard
  Deartoday/Deartoday/Screen/CheckTimeTravelDetail/Controller/CheckTimeTravelDetailViewController.swift
  Deartoday/Deartoday/Screen/CheckTimeTravelDetail/View/PastDialogCollectionViewCell.swift
  Deartoday/Deartoday/Screen/CheckTimeTravelDetail/View/PastDialogCollectionViewCell.xib
  Deartoday/Deartoday/Screen/CheckTimeTravelDetail/View/PresentDialogCollectionViewCell.swift
  Deartoday/Deartoday/Screen/CheckTimeTravelDetail/View/PresentDialogCollectionViewCell.xib
  Deartoday/Deartoday/Screen/CheckTimeTravelDetail/View/TravelAnswerCollectionViewCell.swift
  Deartoday/Deartoday/Screen/CheckTimeTravelDetail/View/TravelAnswerCollectionViewCell.xib
  Deartoday/Deartoday/Screen/CheckTimeTravelDetail/View/TravelChatCollectionViewCell.swift
  Deartoday/Deartoday/Screen/CheckTimeTravelDetail/View/TravelInfoCollectionReusableView.xib
Labels: 경만, 레이아웃, 코드리뷰, P0

#114 [Feat] Layout 상세
  Deartoday/Deartoday/Global/Extension/UILabel+.swift
  Deartoday/Deartoday/Screen/CheckTimeTravelDetail/Controller/CheckTimeTravelDetailViewController.swift
  Deartoday/Deartoday/Screen/CheckTimeTravelDetail/View/PastDialogCollectionViewCell.swift
  Deartoday/Deartoday/Screen/CheckTimeTravelDetail/View/PastDialogCollectionViewCell.xib
  Deartoday/Deartoday/Screen/CheckTimeTravelDetail/View/PresentDialogCollectionViewCell.swift
  Deartoday/Deartoday/Screen/CheckTimeTravelDetail/View/PresentDialogCollectionViewCell.xib
  Deartoday/Deartoday/Screen/CheckTimeTravelDetail/View/TravelAnswerCollectionViewCell.swift
  Deartoday/Deartoday/Screen/CheckTimeTravelDetail/View/TravelAnswerCollectionViewCell.xib
  Deartoday/Deartoday/Screen/CheckTimeTravelDetail/View/TravelChatCollectionViewCell.xib
Labels: 경만, 레이아웃, 코드리뷰, P0

#115 [Chore] 파일 관리
  Deartoday/Deartoday.xcodeproj/project.pbxproj
  Deartoday/Deartoday/Screen/CheckTimeTravelDetail/Model/CheckTimeTravelDetailDataModel.swift
  Deartoday/Deartoday/Screen/CheckTimeTravelDetail/View/TravelChatCollectionViewCell.swift
  Deartoday/Deartoday/Screen/CheckTimeTravelDetail/View/TravelChatCollectionViewCell.xib
  Deartoday/Deartoday/Screen/CheckTimeTravelDetail/View/TravelInfoCollectionViewCell.swift
  Deartoday/Deartoday/Screen/CheckTimeTravelDetail/View/TravelInfoCollectionViewCell.xib
  Deartoday/Deartoday/Screen/CheckTimeTravelDetail/View/Xibs/PastDialogCollectionViewCell.xib
  Deartoday/Deartoday/Screen/CheckTimeTravelDetail/View/Xibs/PastImageCollectionViewCell.xib
  Deartoday/Deartoday/Screen/CheckTimeTravelDetail/View/Xibs/PresentDialogCollectionViewCell.xib
  Deartoday/Deartoday/Screen/CheckTimeTravelDetail/View/Xibs/TravelAnswerCollectionViewCell.xib
  Deartoday/Deartoday/Screen/CheckTimeTravelDetail/View/Xibs/TravelInfoCollectionReusableView.xib
Labels: 경만, 코드리뷰, P0, 프로젝트

#116 [Feat] setting UI 구현
  Deartoday/Deartoday.xcodeproj/project.pbxproj
  Deartoday/Deartoday/Screen/Setting/Controller/SettingViewController.swift
  Deartoday/Deartoday/Screen/Setting/Setting.storyboard
  Deartoday/Deartoday/Screen/Setting/View/SettingTableViewCell.swift
  Deartoday/Deartoday/Screen/Setting/View/SettingTableViewCell.xib
Labels: 찬마, 레이아웃, 코드리뷰, 오류해결, P2, 프로젝트

#118 [Chore] 설정뷰 코드리뷰 반영
  Deartoday/Deartoday/Screen/Setting/Controller/SettingViewController.swift
  Deartoday/Deartoday/Screen/Setting/Setting.storyboard
  Deartoday/Deartoday/Screen/Setting/View/SettingTableViewCell.swift
Labels: 찬마, 코드리뷰, P2, 프로젝트

#122 [Chore] 1차 testflight flow
  Deartoday/Deartoday/Global/Extension/UIViewController+.swift
  Deartoday/Deartoday/Resource/Support/Info.plist
  Deartoday/Deartoday/Screen/Onboarding/Controller/LetterOnboardingViewController.swift
  Deartoday/Deartoday/Screen/Onboarding/Controller/PlayTapeOnboardingViewController.swift
  Deartoday/Deartoday/Screen/Onboarding/Onboarding.storyboard
Labels: 경만, 코드리뷰, P0, 프로젝트

#126 [Hotfix] QA 반영
  Deartoday/Deartoday/Screen/Main/Base.lproj/Main.storyboard
  Deartoday/Deartoday/Screen/Main/Controller/MainViewController.swift
Labels: 경만, 코드리뷰, P0, 프로젝트

#127 [Hotfix] 푸시 알림 오지 않는 이슈 해결 (#124)
  Deartoday/Deartoday/Resource/Support/AppDelegate.swift
Labels: 소깡, P0, 프로젝트

#129 [Hotfix] 추가 QA 반영
  Deartoday/Deartoday/Screen/CheckMessage/Controller/CheckMessageViewController.swift
  Deartoday/Deartoday/Screen/CheckTimeTravel/Controller/CheckTimeTravelViewController.swift
  Deartoday/Deartoday/Screen/Main/Base.lproj/Main.storyboard
  Deartoday/Deartoday/Screen/Main/Controller/MainViewController.swift
Labels: 경만, 레이아웃, 코드리뷰, 프로젝트

#130 [Chore] 소셜로그인 코드 수정
  Deartoday/Deartoday/Network/API/Login/LoginAPI.swift
  Deartoday/Deartoday/Network/DataModel/Login/LoginRequest.swift
  Deartoday/Deartoday/Network/Service/Login/LoginService.swift
  Deartoday/Deartoday/Resource/Support/AppDelegate.swift
  Deartoday/Deartoday/Resource/Support/SceneDelegate.swift
  Deartoday/Deartoday/Screen/Initial/Controller/InitialViewContoller.swift
Labels: 찬마, 서버통신, 코드리뷰, P0, 프로젝트

#132 [Hotfix] 시간여행 디자인 1차 QA 반영 (#128)
  Deartoday/Deartoday/Screen/Dialog/Controller/DialogViewController+.swift
  Deartoday/Deartoday/Screen/Dialog/Controller/DialogViewController.swift
  Deartoday/Deartoday/Screen/TimeTravel/Controller/TimeTravelViewController.swift
  Deartoday/Deartoday/Screen/TimeTravel/View/TimeTravelView.swift
Labels: 소깡, 오류해결, P0

#134 [Feat] button 관련 문제 해결
  Deartoday/Deartoday/Screen/Main/Base.lproj/Main.storyboard
  Deartoday/Deartoday/Screen/Main/Controller/MainViewController.swift
Labels: 경만, 오류해결, 프로젝트

#136 [Feat] color 변경
  Deartoday/Deartoday/Screen/Main/Base.lproj/Main.storyboard
Labels: 경만, 코드리뷰, 오류해결, 프로젝트

#137 [Hotfix] 대화방 POST Written Date 오류 수정 (#135)
  Deartoday/Deartoday/Screen/Dialog/Controller/DialogViewController.swift
Labels: 소깡, 서버통신, 오류해결, P0

#140 [Hotfix] 대화방 POST 오류 해결 (#139)
  Deartoday/Deartoday/Screen/Dialog/Controller/DialogViewController.swift
Labels: 소깡, 서버통신, 오류해결, P0

#141 [Feat] 데모데이 시연 플로우
  Deartoday/Deartoday/Resource/Support/Info.plist
  Deartoday/Deartoday/Resource/Support/SceneDelegate.swift
  Deartoday/Deartoday/Screen/Main/Base.lproj/Main.storyboard
  Deartoday/Deartoday/Screen/Onboarding/Controller/LetterOnboardingViewController.swift
Labels: 경만, 코드리뷰, 프로젝트

#143 [Refactor] 리팩토링
  Deartoday/Deartoday/Global/Constant/Storyboard.swift
  Deartoday/Deartoday/Global/Constant/ViewController.swift
  Deartoday/Deartoday/Global/Extension/UIViewController+.swift
  Deartoday/Deartoday/Screen/CheckMessage/Controller/CheckMessageViewController.swift
  Deartoday/Deartoday/Screen/CheckTimeTravel/Controller/CheckTimeTravelViewController.swift
  Deartoday/Deartoday/Screen/CheckTimeTravelDetail/Controller/CheckTimeTravelDetailViewController.swift
  Deartoday/Deartoday/Screen/Main/Base.lproj/Main.storyboard
  Deartoday/Deartoday/Screen/Main/Controller/MainViewController.swift
Labels: 경만, 코드리뷰
