Repository TeamDearToday/Deartoday-iOS, pull requests merged in 2022-08, with the labels that each got.

#146 [Chore] 리팩토링
  Deartoday/Deartoday/Global/Extension/UIFont+.swift
  Deartoday/Deartoday/Resource/Asset/Assets.xcassets/soundon.imageset/Contents.json
  Deartoday/Deartoday/Screen/Initial/Controller/InitialViewContoller.swift
  Deartoday/Deartoday/Screen/Onboarding/Controller/OnboardingViewController.swift
  Deartoday/Deartoday/Screen/Onboarding/Controller/PlayTapeOnboardingViewController.swift
  Deartoday/Deartoday/Screen/Onboarding/Onboarding.storyboard
  Deartoday/Deartoday/Screen/Splash/Controller/SplashViewController.swift
Labels: 찬마, 레이아웃, 코드리뷰, 오류해결, P0

#148 [Feat] 메시지 확인 뷰 UI 코드로 재구현
  Deartoday/Deartoday.xcodeproj/project.pbxproj
  Deartoday/Deartoday/Global/Extension/UIViewController+.swift
  Deartoday/Deartoday/Screen/CheckMessage/Controller/CheckMessageViewController.swift
  Deartoday/Deartoday/Screen/CheckMessage/Model/CheckMessageDataModel.swift
  Deartoday/Deartoday/Screen/CheckMessage/View/MessageCollectionViewCell.swift
  Deartoday/Deartoday/Screen/CheckMessage/View/MessageCollectionViewCell.xib
  Deartoday/Deartoday/Screen/Main/Controller/MainViewController.swift
Labels: 경만, 코드리뷰

#149 [Feat] Message Detail 코드로 다시 구현
  Deartoday/Deartoday.xcodeproj/project.pbxproj
  Deartoday/Deartoday/Screen/CheckMessage/Controller/CheckMessageViewController.swift
  Deartoday/Deartoday/Screen/CheckMessage/Controller/MessageDetailViewController.swift
  Deartoday/Deartoday/Screen/CheckMessageDetail/CheckMessageDetail.storyboard
  Deartoday/Deartoday/Screen/CheckMessageDetail/Controller/CheckMessageDetailViewController.swift
  Deartoday/Deartoday/Screen/CheckMessageDetail/View/CheckMessageDetailView.swift
Labels: 경만, 코드리뷰

#150 [Feat] Main UI 코드로 구현
  Deartoday/Deartoday.xcodeproj/project.pbxproj
  Deartoday/Deartoday/Global/Extension/UIViewController+.swift
  Deartoday/Deartoday/Resource/Support/Info.plist
  Deartoday/Deartoday/Resource/Support/SceneDelegate.swift
  Deartoday/Deartoday/Screen/Initial/Controller/InitialViewContoller.swift
  Deartoday/Deartoday/Screen/Main/Base.lproj/Main.storyboard
  Deartoday/Deartoday/Screen/Main/Controller/MainNavigationController.swift
  Deartoday/Deartoday/Screen/Main/Controller/MainViewController.swift
  Deartoday/Deartoday/Screen/Main/Model/MainModel.swift
  Deartoday/Deartoday/Screen/Main/View/MainView.swift
Labels: 경만, 코드리뷰

#151 [Feat] Setting UI 코드로 구현
  Deartoday/Deartoday.xcodeproj/project.pbxproj
  Deartoday/Deartoday/Global/Extension/UIButton+.swift
  Deartoday/Deartoday/Screen/Initial/Controller/InitialViewContoller.swift
  Deartoday/Deartoday/Screen/Setting/Controller/SettingViewController.swift
  Deartoday/Deartoday/Screen/Setting/Setting.storyboard
  Deartoday/Deartoday/Screen/Setting/View/SettingTableViewCell.swift
  Deartoday/Deartoday/Screen/Setting/View/SettingTableViewCell.xib
Labels: 찬마, 코드리뷰
